robot:

  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    publish_rate: 20
    joints:
      - joint1_f
      - joint2_f
      - joint1_b
      - joint2_b

    gains: # Required because we're controlling an effort interface
      joint1_f: {p: 32,  d: 0, i: 0.1, i_clamp: 1}
      joint2_f: {p: 32,  d: 0, i: 0.1, i_clamp: 1}
      joint1_b: {p: 32,  d: 0, i: 0.1, i_clamp: 1}
      joint2_b: {p: 32,  d: 0, i: 0.1, i_clamp: 1}

    state_publish_rate:  20          # Override default
    action_monitor_rate: 20            # Override default
    stop_trajectory_duration: 0        # Override default

  claw_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    publish_rate: 20
    joints:
      - joint_garra_ap
      - joint_garra_tracao_f1
      - joint_garra_tracao_f2
      - joint_garra_tracao_b1
      - joint_garra_tracao_b2

    gains: # Required because we're controlling an effort interface
      joint_garra_ap: {p: 32,  d: 0, i: 0.1, i_clamp: 1}
      joint_garra_tracao_f1: {p: 32,  d: 0, i: 0.1, i_clamp: 1}
      joint_garra_tracao_f2: {p: 32,  d: 0, i: 0.1, i_clamp: 1}
      joint_garra_tracao_b1: {p: 32,  d: 0, i: 0.1, i_clamp: 1}
      joint_garra_tracao_b2: {p: 32,  d: 0, i: 0.1, i_clamp: 1}

    state_publish_rate:  20          # Override default
    action_monitor_rate: 20            # Override default
    stop_trajectory_duration: 0        # Override default

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20
