robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  # Position Controllers ---------------------------------------
  joint_1f_controller:
    type: effort_controllers/JointPositionController
    joint: joint1_f
    pid: {p: 32.0, i: 0.01, d: 0.0}

  joint_2f_controller:
    type: effort_controllers/JointPositionController
    joint: joint2_f
    pid: {p: 32.0, i: 0.01, d: 0.0}

  joint_1b_controller:
    type: effort_controllers/JointPositionController
    joint: joint1_t
    pid: {p: 32.0, i: 0.01, d: 0.0}

  joint_2b_controller:
    type: effort_controllers/JointPositionController
    joint: joint2_t
    pid: {p: 32.0, i: 0.01, d: 0.0}

  claw_1c_controller:
    type: effort_controllers/JointPositionController
    joint: joint_garra_ap
    pid: {p: 32.0, i: 0.01, d: 0.0}

  claw_1f_controller:
    type: effort_controllers/JointPositionController
    joint: joint_garra_tracao_f1
    pid: {p: 32.0, i: 0.01, d: 0.0}

  claw_2f_controller:
    type: effort_controllers/JointPositionController
    joint: joint_garra_tracao_f2
    pid: {p: 32.0, i: 0.01, d: 0.0}

  claw_1b_controller:
    type: effort_controllers/JointPositionController
    joint: joint_garra_tracao_t1
    pid: {p: 32.0, i: 0.01, d: 0.0}

  claw_2b_controller:
    type: effort_controllers/JointPositionController
    joint: joint_garra_tracao_t2
    pid: {p: 32.0, i: 0.01, d: 0.0}

  # Velocity Controllers ---------------------------------------
  traction_1c_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_eixo_tracao_ap
    pid: {p: 32.0, i: 0.01, d: 0.0}

  traction_1f_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_eixo_tracao_f1
    pid: {p: 32.0, i: 0.01, d: 0.0}

  traction_2f_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_eixo_tracao_f2
    pid: {p: 32.0, i: 0.01, d: 0.0}

  traction_1b_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_eixo_tracao_t1
    pid: {p: 32.0, i: 0.01, d: 0.0}

  traction_2b_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_eixo_tracao_t2
    pid: {p: 32.0, i: 0.01, d: 0.0}
