<?xml version="1.0"?>
<robot name="elir" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="chassisHeight" value="0.1"/>
  <xacro:property name="chassisLength" value="0.4"/>
  <xacro:property name="chassisWidth" value="0.2"/>
  <xacro:property name="chassisMass" value="50"/>

  <xacro:property name="casterRadius" value="0.04"/>
  <xacro:property name="casterMass" value="3"/>

  <xacro:property name="wheelWidth" value="0.05"/>
  <xacro:property name="wheelRadius" value="0.1"/>
  <xacro:property name="wheelPos" value="0.05"/>
  <xacro:property name="wheelMass" value="5"/>

  <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.1"/>

  <!-- Dimensoes da unidade de apoio -->
	<xacro:property name="l_ap" value="0.225" />
	<xacro:property name="h_ap" value="0.120" />
	<xacro:property name="w_ap" value="0.14" />

	<!-- Dimensoes da caixa eletronica -->
	<xacro:property name="l_eletr_ap" value="0.16" />
	<xacro:property name="h_eletr_ap" value="0.12" />
	<xacro:property name="w_eletr_ap" value="0.14" />

	<!-- Suporte da garra da unidade de apoio -->

	<!-- Dimensoes do sup_apoio -->
	<xacro:property name="l_sup_ap" value="0.036" />
	<xacro:property name="h_sup_ap" value="0.0470" />
	<xacro:property name="w_sup_ap" value="0.140" />


	<!-- Dimensoes do link1 -->
	<xacro:property name="l_link1_1" value="0.0800" />
	<xacro:property name="h_link1_1" value="0.0946" />
	<xacro:property name="w_link1_1" value="0.040" />
	<xacro:property name="l_link1_2" value="0.1163" />
	<xacro:property name="h_link1_2" value="0.1016" />
	<xacro:property name="w_link1_2" value="0.1056" />

	<!-- Posicao do link1 -->
	<xacro:property name="x_link1_1" value="-0.0125" />
	<xacro:property name="y_link1_1" value="0.0" />
	<xacro:property name="z_link1_1" value="0.0" />


	<!-- Posicao da junta1 -->
	<xacro:property name="x_joint1" value="0.092" />
	<xacro:property name="y_joint1" value="0.0" />
	<xacro:property name="z_joint1" value="0.0" />

	<!-- Angulo da junta1 -->
	<xacro:property name="angle_joint1" value="0.5235987755982988" />

	<!-- Dimensoes do link2 -->
	<xacro:property name="l_link2" value="0.380" />
	<xacro:property name="h_link2" value="0.050" />
	<xacro:property name="w_link2" value="0.080" />

	<!-- Dimensoes do link2 -->
	<xacro:property name="x_link2" value="-0.025" />
	<xacro:property name="y_link2" value="0.0" />
	<xacro:property name="z_link2" value="0.0" />

	<!-- Posicao da junta2 -->
	<xacro:property name="x_joint2" value="0.1465" />
	<xacro:property name="y_joint2" value="0.0" />
	<xacro:property name="z_joint2" value="0.0178" />

	<!-- Angulo da junta2 -->
	<xacro:property name="lower_angle_joint2" value="2.181661564992912" />
	<xacro:property name="upper_angle_joint2" value="1.3089969389957472" />

	<!-- Dimensoes da tracao -->
	<xacro:property name="l_tracao" value="0.3319" />
	<xacro:property name="h_tracao" value="0.1016" />
	<xacro:property name="w_tracao" value="0.1056" />

	<!-- Posicao da tracao em relacao a junta-->
	<xacro:property name="x_tracao" value="-0.0157" />
	<xacro:property name="y_tracao" value="0.0" />
	<xacro:property name="z_tracao" value="-0.0099" />

	<!-- Dimensao dos suportes das garras de tracao-->
	<xacro:property name="l_sup_tracao" value="0.0290" />
	<xacro:property name="h_sup_tracao" value="0.0360" />
	<xacro:property name="w_sup_tracao" value="0.0366" />

	<!-- Posicao da junta3 -->
	<xacro:property name="x_joint3" value="0.33" />
	<xacro:property name="y_joint3" value="0.0" />
	<xacro:property name="z_joint3" value="0.0" />

	<!-- Angulo da junta3 -->
	<xacro:property name="lower_angle_joint3" value="0.5235987755982988" />
	<xacro:property name="upper_angle_joint3" value="2.0943951023931953" />

	<!-- Dimensoes do link4 -->
	<xacro:property name="l_link4" value="0.130" />
	<xacro:property name="h_link4" value="0.030" />
	<xacro:property name="w_link4" value="0.050" />

	<!-- Posicoes do link4 -->
	<xacro:property name="x_link4" value="-0.015" />
	<xacro:property name="y_link4" value="0.0" />
	<xacro:property name="z_link4" value="0.0" />

	<!-- Posicao da junta4 -->
	<xacro:property name="x_joint4" value="0.2857" />
	<xacro:property name="y_joint4" value="0.0" />
	<xacro:property name="z_joint4" value="0.0" />

	<!-- Angulo da junta4 -->
	<xacro:property name="lower_angle_joint4" value="0.7853981633974483" />
	<xacro:property name="upper_angle_joint4" value="0.98" />

	<!-- Dimensoes do busca1 -->
	<xacro:property name="l_busca1_1" value="0.0415" />
	<xacro:property name="h_busca1_1" value="0.1016" />
	<xacro:property name="w_busca1_1" value="0.1016" />

	<xacro:property name="l_busca1_2" value="0.05125" />
	<xacro:property name="h_busca1_2" value="0.0470" />
	<xacro:property name="w_busca1_2" value="0.0240" />

	<!-- Posicoes do busca1 -->
	<xacro:property name="x_busca1_1" value="0.0" />
	<xacro:property name="y_busca1_1" value="0.0" />
	<xacro:property name="z_busca1_1" value="-0.0188" />

	<!-- Dimensoes do busca2 -->
	<xacro:property name="l_busca2" value="0.030" />
	<xacro:property name="h_busca2" value="0.1016" />
	<xacro:property name="w_busca2" value="0.1016" />

	<!-- Posicao da junta 5 -->
	<xacro:property name="x_joint5" value="0.100" />
	<xacro:property name="y_joint5" value="0.0" />
	<xacro:property name="z_joint5" value="0.0" />

	<!-- Angulo da junta 5 -->
	<xacro:property name="lower_angle_joint5" value="0.5235987755982988" />
	<xacro:property name="upper_angle_joint5" value="1.0471975511965976" />


	<!-- Posicao da busca2 -->
	<xacro:property name="x_busca2" value="0.0" />
	<xacro:property name="y_busca2" value="0.0" />
	<xacro:property name="z_busca2" value="0.0" />

	<!-- Dimensoes da busca2_2 -->
	<xacro:property name="l_busca2_2" value="0.0580" />
	<xacro:property name="h_busca2_2" value="0.0400" />
	<xacro:property name="w_busca2_2" value="0.0966" />

	<!-- Posicao da busca2_2 -->
	<xacro:property name="x_busca2_2" value="-0.014" />
	<xacro:property name="y_busca2_2" value="0.0" />
	<xacro:property name="z_busca2_2" value="0.0" />

	<!-- Posicao da busca3 -->
	<xacro:property name="x_joint6" value="0.0690" />
	<xacro:property name="y_joint6" value="0.0" />
	<xacro:property name="z_joint6" value="-0.0461" />

	<xacro:property name="x_joint_centro_busca" value="0.023" />
	<xacro:property name="y_joint_centro_busca" value="0.0" />
	<xacro:property name="z_joint_centro_busca" value="0.0" />

	<!-- Angulo da busca1 -->
	<xacro:property name="angle_joint6" value="0.7853981633974483" />

	<!-- Garra da unidade de apoio -->

	<!-- Posicoes da junta da garra_apoio -->
	<xacro:property name="x_joint_garra_ap" value="0.0000" />
	<xacro:property name="y_joint_garra_ap" value="0.0450" />
	<xacro:property name="z_joint_garra_ap" value="0.0165" />

	<!-- Angulos da garra de apoio -->
	<xacro:property name="upper_angle_joint_garra_ap" value="0.52" />
	<xacro:property name="lower_angle_joint_garra_ap" value="0.0" />

	<!-- Suporte da garra da unidade de busca-->

	<!-- Garra da unidade de busca -->

	<!-- Dimensoes do sup_busca -->
	<xacro:property name="l_sup_busca" value="0.030" />
	<xacro:property name="h_sup_busca" value="0.030" />
	<xacro:property name="w_sup_busca" value="0.1016" />

	<!-- Posicoes da junta da garra_busca -->
	<xacro:property name="x_joint_garra_busca" value="0.0000" />
	<xacro:property name="y_joint_garra_busca" value="0.0420" />
	<xacro:property name="z_joint_garra_busca" value="0.012" />

	<!-- Angulos da garra de busca -->
	<xacro:property name="upper_angle_joint_garra_busca" value="0.52" />
	<xacro:property name="lower_angle_joint_garra_busca" value="0.0" />


	<!-- GARRAS DE TRACAO -->
	<!-- Posicoes das garras de tracao-->
	<xacro:property name="x_joint_garra_tracao1" value="0.0867" />
	<xacro:property name="x_joint_garra_tracao2" value="0.2247" />
	<xacro:property name="y_joint_garra_tracao" value="0.0693" />
	<xacro:property name="z_joint_garra_tracao" value="0.0176" />

	<!-- Angulos da garra de busca -->
	<xacro:property name="upper_angle_joint_garra_tracao" value="0.52" />
	<xacro:property name="lower_angle_joint_garra_tracao" value="0.0" />

	<!-- Posicoes dos frames virtuais -->
	<!-- Apoio -->
	<xacro:property name="x_joint_cabo_ap" value="0.0000" />
	<xacro:property name="y_joint_cabo_ap" value="0.0000" />
	<xacro:property name="z_joint_cabo_ap" value="0.3704" />

	<!-- Busca -->
	<xacro:property name="x_joint_cabo_busca" value="0.0000" />
	<xacro:property name="y_joint_cabo_busca" value="0.0000" />
	<xacro:property name="z_joint_cabo_busca" value="0.0550" />

	<!-- Tracao -->
	<xacro:property name="x_joint_cabo_tracao1" value="0.096" />
	<xacro:property name="x_joint_cabo_tracao2" value="0.231" />
	<xacro:property name="y_joint_cabo_tracao" value="0.0000" />
	<xacro:property name="z_joint_cabo_tracao" value="0.0500" />


  <xacro:include filename="$(find elir_description)/urdf/elir.gazebo" />

  <xacro:include filename="$(find elir_description)/urdf/materials.xacro" />

  <xacro:include filename="$(find elir_description)/urdf/macros.xacro" />

  <link name="caixa_eletronica">
    <visual>
      <geometry>
        <box size="0.16 0.14 0.12"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.16 0.14 0.12"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.16" y="0.14" z="0.12"/>
    </inertial>
  </link>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.225 0.14 0.12"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.225 0.14 0.12"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${40*chassisMass}"/>
      <box_inertia m="${40*chassisMass}" x="0.225" y="0.14" z="0.12"/>
    </inertial>
    <visual>
      <geometry>
        <box size="0.036 0.14 0.047"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0 0 0.0835"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.0835"/>
      <geometry>
        <box size="0.036 0.14 0.047"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0835"/>
      <mass value="${40*chassisMass}"/>
      <box_inertia m="${40*chassisMass}" x="0.036" y="0.14" z="0.047"/>
    </inertial>
  </link>

  <joint name="caixa" type="fixed">
    <parent link="base_link" />
    <child link="caixa_eletronica" />
    <origin xyz="0 0 ${-h_ap/2 + -h_eletr_ap/2}" rpy="0 0 0" />
  </joint>
  <!-- JUNTA 1 -->
  <link name="link1_f">
    <visual>
      <geometry>
        <box size="0.08 0.04 0.0946"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.0275 0.0 0.0"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.0275 0.0 0.0"/>
      <geometry>
        <box size="0.08 0.04 0.0946"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.0275 0.0 0.0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.08" y="0.04" z="0.0946"/>
    </inertial>

    <visual>
      <geometry>
        <box size="0.1163 0.1056 0.1016"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.12565 0.0 0.0"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.12565 0.0 0.0"/>
      <geometry>
        <box size="0.1163 0.1056 0.1016"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.12565 0.0 0.0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.1163" y="0.1056" z="0.1016"/>
    </inertial>
  </link>
  <link name="link1_t">
    <visual>
      <geometry>
        <box size="0.08 0.04 0.0946"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.0275 0.0 0.0"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.0275 0.0 0.0"/>
      <geometry>
        <box size="0.08 0.04 0.0946"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.0275 0.0 0.0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.08" y="0.04" z="0.0946"/>
    </inertial>

    <visual>
      <geometry>
        <box size="0.1163 0.1056 0.1016"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.12565 0.0 0.0"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.12565 0.0 0.0"/>
      <geometry>
        <box size="0.1163 0.1056 0.1016"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.12565 0.0 0.0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.1163" y="0.1056" z="0.1016"/>
    </inertial>
  </link>
  <joint name="joint1_f" type="revolute">
    <parent link="base_link"/>
    <child link="link1_f"/>
    <origin rpy="0 0 0" xyz="0.092 0.0 0.0"/>
    <limit effort="1000.0" lower="-0.4" upper="0.4" velocity="0.5"/>
    <axis xyz="0 0 1"/>
  </joint>
  <joint name="joint1_t" type="revolute">
    <parent link="base_link"/>
    <child link="link1_t"/>
    <origin rpy="0 0 3.141592" xyz="-0.092 0.0 0.0"/>
    <limit effort="1000.0" lower="-0.4" upper="0.4" velocity="0.5"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- JUNTA 2 -->
  <link name="link2_f">
    <visual>
      <geometry>
        <box size="0.38 0.08 0.05"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.165 0.0 0.0"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.165 0.0 0.0"/>
      <geometry>
        <box size="0.38 0.08 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.165 0.0 0.0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.38" y="0.08" z="0.05"/>
    </inertial>
  </link>
  <joint name="joint2_f" type="revolute">
    <parent link="link1_f"/>
    <child link="link2_f"/>
    <origin rpy="0 0 0" xyz="0.1465 0.0 0.0178"/>
    <limit effort="1000.0" lower="-1.5" upper="0.7" velocity="0.5"/>
    <axis xyz="0 1 0"/>
  </joint>
  <link name="link2_t">
    <visual>
      <geometry>
        <box size="0.38 0.08 0.05"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.165 0.0 0.0"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.165 0.0 0.0"/>
      <geometry>
        <box size="0.38 0.08 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.165 0.0 0.0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.38" y="0.08" z="0.05"/>
    </inertial>
  </link>
  <joint name="joint2_t" type="revolute">
    <parent link="link1_t"/>
    <child link="link2_t"/>
    <origin rpy="0 0 0" xyz="0.1465 0.0 0.0178"/>
    <limit effort="1000.0" lower="-1.5" upper="0.7" velocity="0.5"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- TRACAO -->
  <link name="tracao_f">
    <visual>
      <geometry>
        <box size="0.3319 0.1056 0.1016"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.15025 0.0 -0.0099"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.15025 0.0 -0.0099"/>
      <geometry>
        <box size="0.3319 0.1056 0.1016"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.15025 0.0 -0.0099"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.3319" y="0.1056" z="0.1016"/>
    </inertial>

    <visual>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.0867 -0.0693 0.0259"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.0867 -0.0693 0.0259"/>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.0867 -0.0693 0.0259"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.029" y="0.0366" z="0.036"/>
    </inertial>

    <visual>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.2247 -0.0693 0.0259"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.2247 -0.0693 0.0259"/>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.2247 -0.0693 0.0259"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.029" y="0.0366" z="0.036"/>
    </inertial>

    <visual>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.0867 0.0693 0.0259"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.0867 0.0693 0.0259"/>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.0867 0.0693 0.0259"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.029" y="0.0366" z="0.036"/>
    </inertial>

    <visual>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.2247 0.0693 0.0259"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.2247 0.0693 0.0259"/>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.2247 0.0693 0.0259"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.029" y="0.0366" z="0.036"/>
    </inertial>
  </link>
  <joint name="joint3_f" type="revolute">
    <parent link="link2_f"/>
    <child link="tracao_f"/>
    <origin rpy="0 0 0" xyz="0.33 0.0 0.0"/>
    <limit effort="1000.0" lower="-0.1" upper="1.6" velocity="0.5"/>
    <axis xyz="0 1 0"/>
  </joint>
  <link name="tracao_t">
    <visual>
      <geometry>
        <box size="0.3319 0.1056 0.1016"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.15025 0.0 -0.0099"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.15025 0.0 -0.0099"/>
      <geometry>
        <box size="0.3319 0.1056 0.1016"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.15025 0.0 -0.0099"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.3319" y="0.1056" z="0.1016"/>
    </inertial>

    <visual>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.0867 -0.0693 0.0259"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.0867 -0.0693 0.0259"/>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.0867 -0.0693 0.0259"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.029" y="0.0366" z="0.036"/>
    </inertial>

    <visual>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.2247 -0.0693 0.0259"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.2247 -0.0693 0.0259"/>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.2247 -0.0693 0.0259"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.029" y="0.0366" z="0.036"/>
    </inertial>

    <visual>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.0867 0.0693 0.0259"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.0867 0.0693 0.0259"/>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.0867 0.0693 0.0259"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.029" y="0.0366" z="0.036"/>
    </inertial>

    <visual>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
      <origin rpy="0 0 0" xyz="0.2247 0.0693 0.0259"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0.2247 0.0693 0.0259"/>
      <geometry>
        <box size="0.029 0.0366 0.036"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.2247 0.0693 0.0259"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="0.029" y="0.0366" z="0.036"/>
    </inertial>
  </link>
  <joint name="joint3_t" type="revolute">
    <parent link="link2_t"/>
    <child link="tracao_t"/>
    <origin rpy="0 0 0" xyz="0.33 0.0 0.0"/>
    <limit effort="1000.0" lower="-0.1" upper="1.6" velocity="0.5"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- GARRAS -->

  <!-- GARRAS DE APOIO -->
  <link name="garra_ap_dir">
    <visual>
      <geometry>
        <mesh filename="package://elir_description/meshes/garra_apoio_direita.dae"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://elir_description/meshes/garra_apoio_direita.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <box_inertia m="0" x="0" y="0" z="0"/>
    </inertial>
  </link>
  <joint name="joint_garra_ap_dir" type="revolute">
    <parent link="base_link"/>
    <child link="garra_ap_dir"/>
    <origin rpy="0 0 0" xyz="0.0 -0.045 0.0765"/>
    <limit effort="1000.0" lower="-0.0" upper="0.52" velocity="0.5"/>
    <axis xyz="1 0 0"/>
  </joint>
  <link name="garra_ap_esq">
    <visual>
      <geometry>
        <mesh filename="package://elir_description/meshes/garra_apoio_esquerda.dae"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://elir_description/meshes/garra_apoio_esquerda.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <box_inertia m="0" x="0" y="0" z="0"/>
    </inertial>
  </link>
  <joint name="joint_garra_ap_esq" type="revolute">
    <parent link="base_link"/>
    <child link="garra_ap_esq"/>
    <origin rpy="0 0 0" xyz="0.0 0.045 0.0765"/>
    <limit effort="1000.0" lower="-0.52" upper="0.0" velocity="0.5"/>
    <axis xyz="1 0 0"/>
    <mimic joint="joint_garra_ap_dir" multiplier="-1" offset="0"/>
  </joint>

  <!-- GARRAS DE TRACAO -->

  <!-- GARRAS TRACAO DIANTEIRA -->
  <link name="garra_tracao_f_dir_1">
    <visual>
      <geometry>
        <mesh filename="package://elir_description/meshes/garra_tracao_direita.dae"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://elir_description/meshes/garra_tracao_direita.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <box_inertia m="0" x="0" y="0" z="0"/>
    </inertial>
  </link>
  <link name="garra_tracao_f_esq_1">
    <visual>
      <geometry>
        <mesh filename="package://elir_description/meshes/garra_tracao_esquerda.dae"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://elir_description/meshes/garra_tracao_esquerda.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <box_inertia m="0" x="0" y="0" z="0"/>
    </inertial>
  </link>
  <joint name="joint_garra_tracao_f_dir_1" type="revolute">
    <parent link="tracao_f"/>
    <child link="garra_tracao_f_dir_1"/>
    <origin rpy="0 0 0" xyz="0.0867 -0.0693 0.0259"/>
    <limit effort="1000.0" lower="-0.0" upper="0.52" velocity="0.5"/>
    <axis xyz="1 0 0"/>
  </joint>
  <joint name="joint_garra_tracao_f_esq_1" type="revolute">
    <parent link="tracao_f"/>
    <child link="garra_tracao_f_esq_1"/>
    <origin rpy="0 0 0" xyz="0.0867 0.0693 0.0259"/>
    <limit effort="1000.0" lower="-0.52" upper="0.0" velocity="0.5"/>
    <axis xyz="1 0 0"/>
    <mimic joint="joint_garra_tracao_f_dir_1" multiplier="-1" offset="0"/>
  </joint>

  <!-- GARRAS TRACAO TRASEIRA -->
  <link name="garra_tracao_t_dir_1">
    <visual>
      <geometry>
        <mesh filename="package://elir_description/meshes/garra_tracao_direita.dae"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://elir_description/meshes/garra_tracao_direita.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <box_inertia m="0" x="0" y="0" z="0"/>
    </inertial>
  </link>
  <link name="garra_tracao_t_esq_1">
    <visual>
      <geometry>
        <mesh filename="package://elir_description/meshes/garra_tracao_esquerda.dae"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://elir_description/meshes/garra_tracao_esquerda.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <box_inertia m="0" x="0" y="0" z="0"/>
    </inertial>
  </link>
  <joint name="joint_garra_tracao_t_dir_1" type="revolute">
    <parent link="tracao_t"/>
    <child link="garra_tracao_t_dir_1"/>
    <origin rpy="0 0 0" xyz="0.0867 -0.0693 0.0259"/>
    <limit effort="1000.0" lower="-0.0" upper="0.52" velocity="0.5"/>
    <axis xyz="1 0 0"/>
  </joint>
  <joint name="joint_garra_tracao_t_esq_1" type="revolute">
    <parent link="tracao_t"/>
    <child link="garra_tracao_t_esq_1"/>
    <origin rpy="0 0 0" xyz="0.0867 0.0693 0.0259"/>
    <limit effort="1000.0" lower="-0.52" upper="0.0" velocity="0.5"/>
    <axis xyz="1 0 0"/>
    <mimic joint="joint_garra_tracao_t_dir_1" multiplier="-1" offset="0"/>
  </joint>

  <!-- Mudado ate aqui -->
  <!-- SENSORES -->
  <!-- Hokuyo -->
  <link name="laser">
    <visual>
      <geometry>
        <mesh filename="package://elir_description/meshes/hokuyo.dae"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://elir_description/meshes/hokuyo.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <box_inertia m="0" x="0" y="0" z="0"/>
    </inertial>
  </link>
  <joint name="hokuyo_base" type="fixed">
    <parent link="tracao_f"/>
    <child link="laser"/>
    <origin rpy="0 3.661592 3.141592" xyz="0.35 0.0 -0.1"/>
  </joint>

  <!-- Sonares -->
  <link name="obstacle_sonar_down">
    <visual>
      <geometry>
        <mesh filename="package://elir_description/meshes/maxsonar.dae"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://elir_description/meshes/maxsonar.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <box_inertia m="0" x="0" y="0" z="0"/>
    </inertial>
  </link>
  <joint name="obstacle_sonar_down_base" type="fixed">
    <parent link="tracao_f"/>
    <child link="obstacle_sonar_down"/>
    <origin rpy="0 0 0" xyz="0.32 0.0 0.03"/>
  </joint>
  <!-- <link name="obstacle_sonar_up">
    <visual>
      <geometry>
        <mesh filename="package://elir_description/meshes/maxsonar.dae"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://elir_description/meshes/maxsonar.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <box_inertia m="0" x="0" y="0" z="0"/>
    </inertial>
  </link>
  <joint name="obstacle_sonar_up_base" type="fixed">
    <parent link="garra_tracao_f_dir_1"/>
    <child link="obstacle_sonar_up"/>
    <origin rpy="0 0 0" xyz="0.16 0.07 0.11"/>
  </joint> -->
  <link name="ground_sonar">
    <visual>
      <geometry>
        <mesh filename="package://elir_description/meshes/groundsonar.dae"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 .8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://elir_description/meshes/groundsonar.dae"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <box_inertia m="0" x="0" y="0" z="0"/>
    </inertial>
  </link>
  <joint name="ground_sonar_base" type="fixed">
    <parent link="base_link"/>
    <child link="ground_sonar"/>
    <origin rpy="0 0 0" xyz="0.0 0.095 -0.14"/>
  </joint>
<!--
  <link name="footprint" />

  <joint name="base_joint" type="fixed">
    <parent link="footprint"/>
    <child link="chassis"/>
  </joint>
  <link name='chassis'>
    <collision>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
    </inertial>
  </link> -->
<!--
  <joint name="caster_chassis" type="continuous">
    <parent link="chassis"/>
    <child link="caster_wheel"/>
    <origin xyz="0 0 ${casterRadius+chassisHeight+wheelRadius}" rpy="0 0 0" />
    <axis xyz="0 1 0" rpy="0 0 0" />
    <limit effort="100" velocity="100"/>
    <dynamics damping="0.7" friction="1.0" />
  </joint>

  <transmission name="$cassis_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="caster_chassis">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="caster_chassisMotor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>10</mechanicalReduction>
    </actuator>
  </transmission>

  <link name="caster_wheel">
    <collision>
      <origin xyz="0 0 ${casterRadius+chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${casterRadius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${casterRadius+chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${casterRadius}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${casterRadius+chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <mass value="${casterMass}"/>
      <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
    </inertial>
  </link> -->

<!--
  <wheel lr="left" tY="1"/>
  <wheel lr="right" tY="-1"/>
  <wheel_no_effort lr="left" tY="1"/>
  <wheel_no_effort lr="right" tY="-1"/> -->
<!--
  <joint name="fixed_camera" type="fixed">
    <parent link="chassis"/>
    <child link="camera"/>
  </joint>
  <link name="camera">
    <collision>
      <origin xyz="0 0 0.5" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0.5" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 0.5" rpy="0 0 0"/>
      <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
    </inertial>
  </link>
   -->
   </robot>
