<?xml version="1.0"?>
<robot name="mybot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="chassisHeight" value="0.1"/>
  <xacro:property name="chassisLength" value="0.4"/>
  <xacro:property name="chassisWidth" value="0.2"/>
  <xacro:property name="chassisMass" value="50"/>

  <xacro:property name="casterRadius" value="0.04"/>
  <xacro:property name="casterMass" value="3"/>

  <xacro:property name="wheelWidth" value="0.05"/>
  <xacro:property name="wheelRadius" value="0.1"/>
  <xacro:property name="wheelPos" value="0.05"/>
  <xacro:property name="wheelMass" value="5"/>

  <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.1"/>

  <xacro:include filename="$(find mybot_description)/urdf/mybot.gazebo" />

  <xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />

  <xacro:include filename="$(find mybot_description)/urdf/macros.xacro" />


  <link name="footprint" />

  <joint name="base_joint" type="fixed">
    <parent link="footprint"/>
    <child link="chassis"/>
  </joint>
  <link name='chassis'>
    <collision>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
    </inertial>
  </link>
<!--
  <joint name="caster_chassis" type="continuous">
    <parent link="chassis"/>
    <child link="caster_wheel"/>
    <origin xyz="0 0 ${casterRadius+chassisHeight+wheelRadius}" rpy="0 0 0" />
    <axis xyz="0 1 0" rpy="0 0 0" />
    <limit effort="100" velocity="100"/>
    <dynamics damping="0.7" friction="1.0" />
  </joint>

  <transmission name="$cassis_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="caster_chassis">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="caster_chassisMotor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>10</mechanicalReduction>
    </actuator>
  </transmission>

  <link name="caster_wheel">
    <collision>
      <origin xyz="0 0 ${casterRadius+chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${casterRadius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${casterRadius+chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${casterRadius}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${casterRadius+chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <mass value="${casterMass}"/>
      <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
    </inertial>
  </link> -->


  <wheel lr="left" tY="1"/>
  <wheel lr="right" tY="-1"/>
  <wheel_no_effort lr="left" tY="1"/>
  <wheel_no_effort lr="right" tY="-1"/>
<!--
  <joint name="fixed_camera" type="fixed">
    <parent link="chassis"/>
    <child link="camera"/>
  </joint>
  <link name="camera">
    <collision>
      <origin xyz="0 0 0.5" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0.5" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 0.5" rpy="0 0 0"/>
      <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
    </inertial>
  </link>
   -->
</robot>
